#!/usr/bin/env bash
# This script will download the needed data and place it into the correction locations
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR"
wget https://www.dropbox.com/s/v63ok3cx1cn1cug/data_3DMM.tgz 
cd janus/components/pvr
tar -xvf "$DIR"/data_3DMM.tgz
rm "$DIR"/data_3DMM.tgz

cd "$DIR"/pix2face/data/models
wget https://www.dropbox.com/s/b0byw0lb3oecv37/pix2face_unet_cuda75.pt
wget https://www.dropbox.com/s/gg88rbigj1ef4af/pix2face_unet_cuda80.pt
